# Generated by Django 3.2.16 on 2023-05-28 20:42

import apps.Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20230518_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=apps.Products.models.rename_img),
        ),
    ]
